// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy6Q_Cj98ope_dl2GfqWESdRqE9equVPY',
    appId: '1:940144485035:android:b46e7e55935bef665d4dee',
    messagingSenderId: '940144485035',
    projectId: 'lemadatabase',
    storageBucket: 'lemadatabase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIxB3XB903QxzzRSQ_bF67ynj201-zFAo',
    appId: '1:940144485035:ios:b6fef86008704c475d4dee',
    messagingSenderId: '940144485035',
    projectId: 'lemadatabase',
    storageBucket: 'lemadatabase.firebasestorage.app',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtRRONYJVxoBYqgd3ykdodMTqwfgewmgQ',
    appId: '1:940144485035:web:06959334b692bea05d4dee',
    messagingSenderId: '940144485035',
    projectId: 'lemadatabase',
    authDomain: 'lemadatabase.firebaseapp.com',
    storageBucket: 'lemadatabase.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIxB3XB903QxzzRSQ_bF67ynj201-zFAo',
    appId: '1:940144485035:ios:b6fef86008704c475d4dee',
    messagingSenderId: '940144485035',
    projectId: 'lemadatabase',
    storageBucket: 'lemadatabase.firebasestorage.app',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtRRONYJVxoBYqgd3ykdodMTqwfgewmgQ',
    appId: '1:940144485035:web:afd04ff77024a16e5d4dee',
    messagingSenderId: '940144485035',
    projectId: 'lemadatabase',
    authDomain: 'lemadatabase.firebaseapp.com',
    storageBucket: 'lemadatabase.firebasestorage.app',
  );

}